version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=db:5432/app_db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=${SHARED_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15-bookworm
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${SHARED_PASSWORD}
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: