name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'QuotesService/**'
      - 'docker-compose/**'
      - '.github/workflows/e2e-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'


      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright requests
          playwright install --with-deps

      - name: Install dependencies
        working-directory: ./QuotesService
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .  

      - name: Set execute permission for all scripts
        run: chmod +x *.py

      - name: Set permissions
        working-directory: ./QuotesService
        run: |
          sudo chown -R $USER:$USER .
          chmod -R 755 .

      - name: Run application
        working-directory: ./QuotesService
        env:
          DATABASE_URL: localhost:5432/testdb
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          API_KEY: test_api_key
        run: |
          python app.py &
          echo $! > app.pid
          sleep 5
          pytest tests/e2e -v
